from .dashboard_view import DashboardView
from .evaluation_view import EvaluationView
from .file_view import FileView
from .loading_view import LoadingView
from .results_view import ResultsView
from .new_criteria_view import NewCriteriaView
from .edit_criteria_view import EditCriteriaView
from .settings_view import SettingsView
from .all_criteria_view import AllCriteriaView